services:
  emojive-api:
    image: thomasy314/emojive-backend:latest
    container_name: emojive-api
  watchtower:
    image: containrrr/watchtower
    container_name: emojive-watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --cleanup emojive-api
