services:
  emojive-api:
    environment:
      - IP=${IP}
      - PORT=${PORT}
      - NODE_ENV=development
    build:
      context: .
      target: build
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - ${PORT}:${PORT}
    command: npm run dev
